server:
  port: 18119
spring:
  application:
    name: csdnpuller
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/testdb?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2b8
    username: mysql
    password: mysql
  jpa:
    database: mysql
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
  mail:
    default-encoding: utf-8
    host: smtp.abc.cn
    port: 25
    username: sender@senderhost.com
    password: yourpassword
    protocol: smtp
    test-connection: true
blog:
  address: https://blog.csdn.net/diaobatian
email:
  from: abc@youmail.com
  to: reciver1@reciverhost.com,reciver2@reciverhost.com
  title: CSDN RANKS